services:
  - type: web
    name: ai-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install httpx>=0.25.0
      pip install -r requirements.txt
    startCommand: "python app.py"
    plan: free